application: lnconsulting
version: 7
runtime: php55
api_version: 1
threadsafe: true

default_expiration: "7d"

handlers:
- url: /files
  static_dir: files
  application_readable: true

- url: /themes/(.+)/assets/(.+)
  static_files: themes/\1/assets/\2
  upload: themes/(.+)/assets/(.+) 

- url: /.*
  script: index.php
